### ISSUE TITLE
Conda env create stalls and loops indefinitely

### ISSUE THREAD

**Issue by skercher** [vye16/slahmr#1]
### Current Behavior
Conda install hangs and loops indefinitely

### Steps to Reproduce
It stalls out when executing the following command:
`conda env create -f env.yaml`

It runs correctly if you comment out `conda-forge` in env.yaml but it doesn't create the environment.

### Expected Behavior
Conda installs all packages successfully and activates the environment without errors

### Environment Information
`conda info`
   ```
     active environment : base
     active env location : /home/shawn/anaconda3
        	shell level : 1
   	user config file : /home/shawn/.condarc
 populated config files :
      	conda version : 23.1.0
	conda-build version : 3.22.0
     	python version : 3.9.13.final.0
   	virtual packages : __archspec=1=x86_64
                      	__glibc=2.35=0
                      	__linux=5.19.0=0
                      	__unix=0=0
   	base environment : /home/shawn/anaconda3  (writable)
  	conda av data dir : /home/shawn/anaconda3/etc/conda
  conda av metadata url : None
       	channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                      	https://repo.anaconda.com/pkgs/main/noarch
                      	https://repo.anaconda.com/pkgs/r/linux-64
                      	https://repo.anaconda.com/pkgs/r/noarch
      	package cache : /home/shawn/anaconda3/pkgs
                      	/home/shawn/.conda/pkgs
   	envs directories : /home/shawn/anaconda3/envs
                      	/home/shawn/.conda/envs
           	platform : linux-64
         	user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Linux/5.19.0-32-generic ubuntu/22.04.1 glibc/2.35
            	UID:GID : 1000:1000
         	netrc file : None
       	offline mode : False
```

Please let me know if you need any further information to help reproduce this problem.

Thanks! 
Shawn

**Comment by soyaoki** [comment]
Thank you @Dene33 !

Plus, following worked for me to create the enviroment.

(1) 'apt install cuda-11-6' (maybe needed 'apt install gcc-10 g++-10')

(2) add "gyp" to env.yaml's channels.

(3) rename directory name, "third-party" to "third_party"

I googled and fixed other bugs like numpy downgrade, 'export EGL_DEVICE_ID=1', etc., but I don't remember exactly. Sorry.
Anyway, the code in this repository works!

![image](https://user-images.githubusercontent.com/45820850/223410454-5e8784d5-8e30-47f0-b39c-544d72d13473.png)

**Comment by geopavlakos** [comment]
We have updated the installation instructions, so that the installation is faster. If there are still issues, we give more options for trouble-shooting in the Readme. Please let us know if you still face problems with the installation.
