### ISSUE TITLE
How to estimate accurate 3D positions without fitting?

### ISSUE THREAD

**Issue by lucasjinreal** [vye16/slahmr#13]
How to estimate accurate 3D positions without fitting?

**Comment by geopavlakos** [comment]
For a less accurate result that doesn't require fitting, you can use our initialization, which comes from [PHALP](https://github.com/brjathu/PHALP). However, this doesn't reach the level of accuracy you can get by going through the fitting stages.

**Comment by jinfagang** [comment]
@geopavlakos thank u, which 3d pose model does it use? pare or spin?

**Comment by geopavlakos** [comment]
The model we use is a modification of the network of [our previous work](https://geopavlakos.github.io/multishot/). This is closer to the SPIN network, but with increased robustness to truncations and occlusions from other people, so that it behaves better in videos with multiple people.
