### ISSUE TITLE
Local build SMPL model output data*.npz

### ISSUE THREAD

**Issue by xangs** [vye16/slahmr#14]
How to build an SMPL model locally based on the 'motion_chunks' data? Any ideas ?

**Comment by geopavlakos** [comment]
To load and visualize the data from any of the output folders, you can use the command:
`python run_vis.py --log_root <LOG_ROOT>`
More details about this functionality are provided in the README too.

For some more detailed pointers, you can take a look at the function [load_result](https://github.com/vye16/slahmr/blob/410c15f1085e7474399cf455afe389c3be2ad2a4/slahmr/run_vis.py#L73) which loads the output of a specific npz, and then [render_results](https://github.com/vye16/slahmr/blob/410c15f1085e7474399cf455afe389c3be2ad2a4/slahmr/run_vis.py#L91) is used for the visualization (while inside it, [prep_result_vis](https://github.com/vye16/slahmr/blob/410c15f1085e7474399cf455afe389c3be2ad2a4/slahmr/run_vis.py#L183) loads the body meshes).
