### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by M-Colley** [vye16/slahmr#15]
Hey, thank you very much for providing a Google Colab for exploration. 

However, the Colab does not work for me. 

For example, when running the demo video, I encounter the 

`ModuleNotFoundError: No module named 'tensorboard'`

I can see that this is actually in the requirements.txt. I tried several times to start the Colab from scratch, and I probably could resolve the issues, but I think it would be good for the broader community if you fixed the Colab.

Kind regards

**Comment by geopavlakos** [comment]
Thanks for bringing this to our attention! I believe this was due to a dependency not being installed properly, which was messing with the installation of the other requirements. I have fixed this temporarily. Please let us know if the colab works for you now, or if you have further problems.

**Comment by M-Colley** [comment]
Unfortunately not. The environment crashes. I tried multiple times.

**Comment by geopavlakos** [comment]
Can you specify where this happens? There is an instance, after the first box, where the environment crashes intentionally and restarts, but the rest of the boxes should run smoothly.

**Comment by snitchjinx** [comment]
Hi! Thank you for providing the colab!

I also encountered the same issue.
After I try to run cell #8, it says:
`Traceback (most recent call last):
  File "/content/slahmr/slahmr/run_opt.py", line 8, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/usr/local/envs/slahmr/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'
`

I also tried to install locally and the issue remained.
Would you please take a look of this?
Thank you for your consideration!
