### ISSUE TITLE
Error when running long sequence

### ISSUE THREAD

**Issue by Coral79** [vye16/slahmr#17]
Hi, I had some problems, the code crushed when I tried to run 1000 frames of my video. I saw the default number of input frames is 120. I am wondering if you have tried to run the code on a longer sequence.

Thank you very much!

**Comment by geopavlakos** [comment]
The current optimization schedule behaves better for shorter sequences (e.g., up to 200-300 frames) and we have observed difficulties in optimizing longer sequences. It would probably be preferable to split the sequences in smaller batches first and run slahmr on each one of them.

**Comment by Coral79** [comment]
Hi, thank you very much for the reply. I have noticed for the egobody dataset, you split them into chunks (100 framse). In this case, since the video is optimized in small batches, will each chunk have a different global scale and ground postion?

**Comment by geopavlakos** [comment]
Yes, if the subsequences are optimized independently, the global scale and the ground plane will be different.
