### ISSUE TITLE
mmpose version

### ISSUE THREAD

**Issue by zhenzhiwang** [vye16/slahmr#19]
Hi,

Thanks for sharing your great work! I notice that your code of phalp_plus uses mmpose which has many versions. Could you share the version of mmpose, mmdet and mmcv in your server to let me configure the conda environment easier?

**Comment by geopavlakos** [comment]
We provide [this file](https://github.com/vye16/slahmr/blob/main/env_build.yaml) with the full details regarding the versions of the dependencies we use for our environment.
