### ISSUE TITLE
SMPL fittings in motion_chunks_final looks worse than input

### ISSUE THREAD

**Issue by xiyichen** [vye16/slahmr#20]
Hi,
Nice work! I tested your method on a custom video. The 3D positions look good. However, the SMPL fittings in the final visualization video (motion_chunks_final_000260_src_cam.mp4), as shown in the first screenshot, somehow look worse than those in the input video (input_final_000000_src_cam.mp4), as shown in the second screenshot, especially the feet poses.

<img width="1245" alt="Screenshot 2023-06-25 at 12 40 45" src="https://github.com/vye16/slahmr/assets/50854238/7c275648-1af1-4471-8d46-304f3f255495">

<img width="1245" alt="Screenshot 2023-06-25 at 12 40 57" src="https://github.com/vye16/slahmr/assets/50854238/65c87c54-dde0-45d3-a7b8-2050656cd2aa">

I also runned the optimization on the demo video you provided in the colab notebook, and the SMPL fittings do look better in the motion_chunks_final video. Do you have any idea why the SMPL fittings are worse after optimization in my custom video?

**Comment by geopavlakos** [comment]
Would it be possible to share the original video for us to inspect it?

**Comment by xiyichen** [comment]
Thanks for your quick response. This video is the _bike_ sequence from the [NeuMan](https://github.com/apple/ml-neuman) dataset. It contains 104 frames. You can download the whole dataset from [here](https://docs-assets.developer.apple.com/ml-research/datasets/neuman/dataset.zip).

**Comment by geopavlakos** [comment]
The framerate of the video seems very low (maybe 2-3 fps?). The motion prior we use ([HuMoR](https://geometry.stanford.edu/projects/humor/)) is trained with sequences of 30fps, so this is also expected at test time (based on our observation, 20-25 fps is probably ok too). The lower framerate of the video can be an issue for the optimization of the last stage of slahmr which depends on HuMoR. This can explain the lower quality of the results you observe.

**Comment by xiyichen** [comment]
Thanks for your response. I see the issue. I'll try it on videos with a higher fps.

**Comment by xiyichen** [comment]
I also have a question on optimized the camera parameters. I extracted SMPL parameters, cam_R, cam_t, and the intrinsic matrix from '_000260_world_results.npz' (the last one). However, when I convert the SMPL vertices from the world space to the camera space and project it onto the image, the calibration does not look right:
![smpl_debug](https://github.com/vye16/slahmr/assets/50854238/6a7951bc-fdfd-4d65-9e66-70558b0ed48f)
I wonder if I am using the wrong camera parameters (there are some other camera parameters in _cameras_000260.json) or is there any conversion needed?

**Comment by geopavlakos** [comment]
For this, it's better to check and follow the rendering/visualization functions, to confirm that you are using the right intrinsics/extrinsics parameters and human body coordinates.
