### ISSUE TITLE
How can I speed up the inference when testing on large-scale videos?

### ISSUE THREAD

**Issue by linjing7** [vye16/slahmr#23]
Hi, thanks for your excellent work! I have a question regarding speeding up inference when testing on large-scale videos. In README, You recommend preprocessing in advance. However, the tracking is still run with `batch_size=1`, which is quite slow. Is it possible to use a larger `batch_size` to speed up the tracking? BTW, could you please tell me the advantage of preprocessing in advance?

**Comment by smandava98** [comment]
Hi! Did you manage to figure this out? I am having the same issue :/
