### ISSUE TITLE
4D humans support is missing

### ISSUE THREAD

**Issue by smandava98** [vye16/slahmr#26]
Where does it use the body mesh tracking code for 4D humans?

I just see this:

@dataclass
class Human4DConfig(FullConfig):
    # override defaults if needed
    pass

**Comment by geopavlakos** [comment]
The [tracking command](https://github.com/vye16/slahmr/blob/2c6ee822216c6be0965fc78a28861d9da1da29d6/slahmr/preproc/launch_phalp.py#L27) that we run for preprocessing adopts the tracking pipeline from 4D Humans.
