### ISSUE TITLE
Dual steps in Colab notebook

### ISSUE THREAD

**Issue by smandava98** [vye16/slahmr#29]
Hi. I was playing around with the Colab notebook and was confused on these two commands (preprocessing and optimizing):

python run_opt.py data=video data.seq=test data.root=/content/slahmr/demo run_opt=False run_vis=False
python run_opt.py data=video data.seq=test data.root=/content/slahmr/demo run_opt=True run_vis=False

Are both necessary to run for every video?

**Comment by geopavlakos** [comment]
You can simply run the second command and it will do the preprocessing together with the optimization. Colab decouples the two steps to make monitoring easier.

**Comment by smandava98** [comment]
Awesome, thanks Georgios!
