### ISSUE TITLE
File with motion information

### ISSUE THREAD

**Issue by carlosedubarreto** [vye16/slahmr#32]
Hello. I was able to instal SLAHMR on my windows machine and processed a video.
I would like to know where I can get the file with the information about the motion of the characters and the enviroment?

And how I could load them for analisys and for me to try to load that data in Blender.
I alredy did an importer for 4dhumans and was expecting to have similar data output, but when the process ended i was left with these files
![image](https://github.com/vye16/slahmr/assets/4061130/ddc4a166-96b9-4e8a-8c39-debb203eb4d6)

and I couldnt find any information on how to load it and what the data inside means.

thanks a lot for everything.

**Comment by carlosedubarreto** [comment]
I think I've found.
the information I'm looking for seems to be on those npz files

For example this file i'm showing bellow is on this place
`D:\AI\0_mocap\slahmr_prj\slahmr_main\outputs\logs\video-val\2023-08-02\gymnasts-all-shot-0-0-180\motion_chunks\gymnasts_000400_prior_results.npz`


If you have more information about those data inside the npz files, it would be great, or where can I find more information about them.

![image](https://github.com/vye16/slahmr/assets/4061130/1390be7a-f5b0-43b0-b592-25710dc4ae9e)

**Comment by ediller3** [comment]
@carlosedubarreto Did you figure out a good way to import into blender? I actually tried your script for 4D-Humans and was wondering if you had any luck with this repo as well

**Comment by ediller3** [comment]
Hi @carlosedubarreto, thanks for pointing me to your page! I see you figured out blender support for the humor repo. I was specifically wondering about SLAHMR though, any luck with this one?

**Comment by carlosedubarreto** [comment]
> Hi @carlosedubarreto, thanks for pointing me to your page! I see you figured out blender support for the humor repo. I was specifically wondering about SLAHMR though, any luck with this one?

Hello. Yeah i was able to import slahmr too.
I think it was very similar to 4dhumans, it just had to do  a few things different, but I don't remeber what was different.

**Comment by ediller3** [comment]
> > Hi @carlosedubarreto, thanks for pointing me to your page! I see you figured out blender support for the humor repo. I was specifically wondering about SLAHMR though, any luck with this one?
> 
> Hello. Yeah i was able to import slahmr too. I think it was very similar to 4dhumans, it just had to do a few things different, but I don't remeber what was different.

Do you happen to recall what .npz file from SLAHMR contained the same pose data that 4D Humans provides?

**Comment by carlosedubarreto** [comment]
> > > Hi @carlosedubarreto, thanks for pointing me to your page! I see you figured out blender support for the humor repo. I was specifically wondering about SLAHMR though, any luck with this one?
> > 
> > Hello. Yeah i was able to import slahmr too. I think it was very similar to 4dhumans, it just had to do a few things different, but I don't remeber what was different.
> 
> Do you happen to recall what .npz file from SLAHMR contained the same pose data that 4D Humans provides? 

On the second post of this issue I explain where i found the file.

Its been a while, so i actually dont remember much, but what i remember is that the npz file was not in the same way that 4d humans. It will need some changes.

**Comment by carlosedubarreto** [comment]
Hello @ediller3 , Now I was able to go to the pc, and I found a blend file that will probably help you on this blender import.

Now I remember, things were much more complicated to import in blender since also the SMPL file is different, So I had to remap to another files, I had to map to SMPLX, I think. this SMPLX is the one that has the fingers.

I'm sending the blend file attached here.

[loading_slahmar_import_SMPL.zip](https://github.com/vye16/slahmr/files/13062465/loading_slahmar_import_SMPL.zip)

**Comment by carlosedubarreto** [comment]
Hello @tucker666 
Sorry  I can help much. 
I received some answer somewhere that there is information on the camera movement in some file, but I was not able to get it,
I'm actually not using slhmr becuase its good but it takes too long to process, and from what I'm using the results from 4d humans seems much better for me.

**Comment by vye16** [comment]
Hello sorry for the late reply. To get the final cameras, load the final
`*_world_result.npz` file in the `motion_chunks` directory. The world to
camera transform is given by `cam_R` and `cam_t`. The human parameters are
given in the world coordinate frame.
