### ISSUE TITLE
colab error in the last step

### ISSUE THREAD

**Issue by kotaxyz** [vye16/slahmr#35]
the cells works fine till the last cell i get this error

the code line

def show_local_mp4_video(file_name, width=640, height=480):
  import io
  import base64
  from IPython.display import HTML
  video_encoded = base64.b64encode(io.open(file_name, 'rb').read())
  return HTML(data='''<video width="{0}" height="{1}" alt="test" controls>
                        <source src="data:video/mp4;base64,{2}" type="video/mp4" />
                      </video>'''.format(width, height, video_encoded.decode('ascii')))

import glob
mp4s = glob.glob('/content/slahmr/outputs/logs/video-val/*/*/*_motion_chunks_grid.mp4')
show_local_mp4_video(mp4s[0], width=960, height=720)

here is the error that shows when running 

IndexError                                Traceback (most recent call last)
[<ipython-input-14-c893919ca9cf>](https://localhost:8080/#) in <cell line: 12>()
     10 import glob
     11 mp4s = glob.glob('/content/slahmr/outputs/logs/video-val/*/*/*_motion_chunks_grid.mp4')
---> 12 show_local_mp4_video(mp4s[0], width=640, height=480)

IndexError: list index out of range

**Comment by toyxyz** [comment]
When I run colab, an error occurs from this part.

# run on demo video - preprocessing steps
!source activate slahmr && python run_opt.py data=video data.seq=022691_mpii_test data.root=/content/slahmr/demo run_opt=False run_vis=False

ut_dir /content/slahmr/outputs/logs/video-val/2023-08-06/022691_mpii_test-all-shot-0-0-180
/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0 does not exist
/content/slahmr/demo/slahmr/track_preds/022691_mpii_test does not exist
/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json does not exist
SOURCES {'images': '/content/slahmr/demo/images/022691_mpii_test', 'cameras': '/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0', 'tracks': '/content/slahmr/demo/slahmr/track_preds/022691_mpii_test', 'shots': '/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json'}
/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0 does not exist
/content/slahmr/demo/slahmr/track_preds/022691_mpii_test does not exist
/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json does not exist
DATA SOURCES {'images': '/content/slahmr/demo/images/022691_mpii_test', 'cameras': '/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0', 'tracks': '/content/slahmr/demo/slahmr/track_preds/022691_mpii_test', 'shots': '/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json'}
FOUND 126 FRAMES in /content/slahmr/demo/images/022691_mpii_test
RUNNING PHALP ON /content/slahmr/demo/images/022691_mpii_test
PROCESS MainProcess ()
PHALP DIR /content/slahmr/slahmr/preproc
cd /content/slahmr/slahmr/preproc; CUDA_VISIBLE_DEVICES=0 python track.py video.source=/content/slahmr/demo/slahmr/phalp_out video.output_dir=022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test overwrite=False detect_shots=True video.extract_video=False render.enable=False
Traceback (most recent call last):
  File "/content/slahmr/slahmr/preproc/track.py", line 10, in <module>
    from phalp.configs.base import FullConfig
ModuleNotFoundError: No module named 'phalp'
Error executing job with overrides: ['data=video', 'data.seq=022691_mpii_test', 'data.root=/content/slahmr/demo', 'run_opt=False', 'run_vis=False']
Traceback (most recent call last):
  File "/content/slahmr/slahmr/run_opt.py", line 175, in main
    dataset = get_dataset_from_cfg(cfg)
  File "/content/slahmr/slahmr/data/dataset.py", line 41, in get_dataset_from_cfg
    check_data_sources(args)
  File "/content/slahmr/slahmr/data/dataset.py", line 70, in check_data_sources
    preprocess_tracks(args.sources.images, args.sources.tracks, args.sources.shots)
  File "/content/slahmr/slahmr/data/vidproc.py", line 40, in preprocess_tracks
    phalp.process_seq(
  File "/content/slahmr/slahmr/preproc/launch_phalp.py", line 60, in process_seq
    os.rename(f"{res_dir}/demo_{name}.pkl", res_path)
FileNotFoundError: [Errno 2] No such file or directory: '022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test/results/demo_022691_mpii_test.pkl' -> '022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test/022691_mpii_test.pkl'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by SunSoul** [comment]
> When I run colab, an error occurs from this part.
> 
> # run on demo video - preprocessing steps
> !source activate slahmr && python run_opt.py data=video data.seq=022691_mpii_test data.root=/content/slahmr/demo run_opt=False run_vis=False
> 
> ut_dir /content/slahmr/outputs/logs/video-val/2023-08-06/022691_mpii_test-all-shot-0-0-180 /content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0 does not exist /content/slahmr/demo/slahmr/track_preds/022691_mpii_test does not exist /content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json does not exist SOURCES {'images': '/content/slahmr/demo/images/022691_mpii_test', 'cameras': '/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0', 'tracks': '/content/slahmr/demo/slahmr/track_preds/022691_mpii_test', 'shots': '/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json'} /content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0 does not exist /content/slahmr/demo/slahmr/track_preds/022691_mpii_test does not exist /content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json does not exist DATA SOURCES {'images': '/content/slahmr/demo/images/022691_mpii_test', 'cameras': '/content/slahmr/demo/slahmr/cameras/022691_mpii_test/shot-0', 'tracks': '/content/slahmr/demo/slahmr/track_preds/022691_mpii_test', 'shots': '/content/slahmr/demo/slahmr/shot_idcs/022691_mpii_test.json'} FOUND 126 FRAMES in /content/slahmr/demo/images/022691_mpii_test RUNNING PHALP ON /content/slahmr/demo/images/022691_mpii_test PROCESS MainProcess () PHALP DIR /content/slahmr/slahmr/preproc cd /content/slahmr/slahmr/preproc; CUDA_VISIBLE_DEVICES=0 python track.py video.source=/content/slahmr/demo/slahmr/phalp_out video.output_dir=022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test overwrite=False detect_shots=True video.extract_video=False render.enable=False Traceback (most recent call last): File "/content/slahmr/slahmr/preproc/track.py", line 10, in from phalp.configs.base import FullConfig ModuleNotFoundError: No module named 'phalp' Error executing job with overrides: ['data=video', 'data.seq=022691_mpii_test', 'data.root=/content/slahmr/demo', 'run_opt=False', 'run_vis=False'] Traceback (most recent call last): File "/content/slahmr/slahmr/run_opt.py", line 175, in main dataset = get_dataset_from_cfg(cfg) File "/content/slahmr/slahmr/data/dataset.py", line 41, in get_dataset_from_cfg check_data_sources(args) File "/content/slahmr/slahmr/data/dataset.py", line 70, in check_data_sources preprocess_tracks(args.sources.images, args.sources.tracks, args.sources.shots) File "/content/slahmr/slahmr/data/vidproc.py", line 40, in preprocess_tracks phalp.process_seq( File "/content/slahmr/slahmr/preproc/launch_phalp.py", line 60, in process_seq os.rename(f"{res_dir}/demo_{name}.pkl", res_path) FileNotFoundError: [Errno 2] No such file or directory: '022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test/results/demo_022691_mpii_test.pkl' -> '022691_mpii_test/phalp_out//content/slahmr/demo/images/022691_mpii_test/022691_mpii_test.pkl'
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

the same error

**Comment by HenrySomeCode** [comment]
me too.

**Comment by geopavlakos** [comment]
There were some changes in the dependencies that made colab to fail. We have updated colab and it works now. Please give it another try.
