### ISSUE TITLE
Google Colab not working

### ISSUE THREAD

**Issue by RohaanA** [vye16/slahmr#46]
Hi,

I was trying to run the official colab file provided for this project. However, It took really long time during this phase,

<img width="750" alt="image" src="https://github.com/vye16/slahmr/assets/75722072/367291b7-4651-4cdb-bc20-388081ae402a">
<br> (as u can see, it took 56 minutes during this installation).

Moreover, at the end of the notebook there is no video output to be played, even though no error is produced when I run the model.

<img width="759" alt="image" src="https://github.com/vye16/slahmr/assets/75722072/d1d3464a-f45d-4edd-914c-94f45341f89c">

<img width="748" alt="image" src="https://github.com/vye16/slahmr/assets/75722072/dcfab14c-a332-44b1-8091-3d1ebed0b218">
<br> (this error happens as there is no mp4 video to be played)

**Comment by geopavlakos** [comment]
Thank you for pointing this out. There were some changes in the dependencies that made colab to fail. We have updated colab and it works now. Please give it another try.

Unfortunately, due to the many dependencies, the installation on colab can be pretty slow.
