### ISSUE TITLE
Could you please provide information about output?

### ISSUE THREAD

**Issue by Talegqz** [vye16/slahmr#8]
Thank you for sharing your work as an open-source project. I appreciate your efforts and the quality of your code.

I recently ran the code and obtained a lot of output, but I'm not sure what it means. Would it be possible to provide some introductory information about the output?

Thank you for your help, and I look forward to your response.

**Comment by vye16** [comment]
Hi, thanks for bringing this up. I updated the README with an explanation of the outputs in this commit [daee052](https://github.com/vye16/slahmr/commit/daee0526c68a452cd65fd6203e8fbbcd8bcdbbb7) -- hopefully it's helpful!

**Comment by zhan-xu** [comment]
Hi @Talegqz @vye16 , seems run_vis.py didn't output *.npy from my side. I wonder if this only happens to me.
